# Generated by Django 4.2.3 on 2023-08-10 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='inputid',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='inputpw',
            new_name='password',
        ),
    ]
